// "use client";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import CustomProvider from '@/components/CustomProvider'
import DarkModeButton from '@/components/DarkModeButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: "/next.svg",
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body >
        <CustomProvider>
          {children}
          <DarkModeButton />
        </CustomProvider>
      </body>
    </html>
  )
}

